### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JStika** [i-lateral/silverstripe-users#1]
Hi,

how can I to use your code to be form in line, in my page, e.g. Security/login?  
Need I create AccountPage?
Can you help me, please?

**Comment by mlewis-everley** [comment]
Hi Jaroslav,

As usual github didn't notify of this issue!

Do you mean that you want your form labels to be to the left of the form inputs (rather than above them)?

If so, the users module uses the standard silverstripe forms templates, you can also extend the Users_Account_Controller and add update the forms directly through your extension by adding the following methods

```
class AccountExtension extends Extension {    
    public function updateEditAccountForm($form) {
        $form->addExtraClass("columns");
    }

    public function updateChangePasswordForm($form) {
        $form->addExtraClass("columns");
    }
}
```

You can then add a .columns label to your CSS and style the forms that way.

Hope that helps?

Cheers,

Mo

**Comment by JStika** [comment]
Thx.
